### PR TITLE
fix categories that were listed incorrectly

### PR DESCRIPTION
**Pull request by m4v15**
Have copy and pasted from the constants file to ensure no mistakes

Any change you just wanna merge this @mattlub or @des-des as it is wrong for the data-entry and events team atm

### CODE REVIEW

**Comment by mattlub** [comment]
didn't we do this before? How many mistakes are there?

**Comment by mattlub** [comment]
also- should we change 'miscellaneous' to 'other' in events categories? Or at least add 'other'?

**Comment by m4v15** [comment]
Yeah I think we should, but not in this PR

**Comment by m4v15** [comment]
Actually, none other than cultural event => culture

I guess this way was just making sure there were definitely no other mistakes.

**Comment by Suuuuha** [comment]
@m4v15 @mattlub in my opinion, in the accessibility options -  'place for guide dog' could be changed to 'guide dog allowed' or sth for clarity. since in israel there are no places for guide dog but dogs might be allowed if the place is friendly accessible.

**Comment by mattlub** [comment]
@m4v15 I think if it's gonna be json, we should just link to the constants file, so we don't have to change things in multiple places.

**Comment by m4v15** [comment]
lol did not notice your comment here @Suuuuha. Again, we can definitely change some categories, but this PR is for fixing the currently wrong docs, **not** for changing the categories. Raise an issue?

@mattlub Yes you are probably right, I will do this now, sorry. Back to how it was originally lol.

**Review by des-des — APPROVED** [review]

**Pull request merged**
