### PR TITLE
Object to dot notation

### PR DESCRIPTION
**Pull request by m4v15**
addresses #144

### CODE REVIEW

**Review by mattlub — APPROVED** [review]

**Comment by des-des** [comment]
@m4v15 I think this might get someone into all kinds of trouble if somewhere down the line we needed nested objects in body..

**Comment by des-des** [comment]
@m4v15 what about this: https://github.com/Automattic/mongoose/issues/5285#issuecomment-309124718

**Comment by m4v15** [comment]
Yeah I did sort of think this, I think we might be better just making this a helper function we can call when we need it, as we might need it when we do field permissions:

- When the req.body comes in for the update it will be a nested object, we might need to flatten this to do our permission field by field check before doing the update in mongoose

I think what I will do is add it as a helper functions, and use that as a pre update and findoneandupdate hook, and then it can be used before the field permission as well if necessary

For now I will put this on hold until #122 and #146 are done

**Comment by des-des** [comment]
I think this should happen final step before mongoose call

**Comment by m4v15** [comment]
hey I'm cleaning my github up, presumably I can close and delete this branch @des-des @Karyum ?

**Comment by m4v15** [comment]
actually I can just unassign myself 😅

**Pull request closed without merging**
