### PR TITLE
adds testing for the refresh token

### LINKED ISSUE #175: adds testing for the refresh token functionality
related to #139 #102 

using [@m4v15 branch](https://github.com/foundersandcoders/open-tourism-platform/tree/refreshTry) for reference

### PR DESCRIPTION
**Pull request by Karyum**
close #175 #143 #139 #102

### CODE REVIEW

**Comment by m4v15** [comment]
🎉 Amazing! Does this work? What more did you have to do from my branch?

**Comment by Karyum** [comment]
@m4v15 lol nothing, you got it perfectly working before, i think this was just you adding testing for the refresh token.

tested it on the data entry, and it works like a charm :sweat_smile:

**Comment by m4v15** [comment]
Oh wow, I thought I couldn't get it working, shouldn't have doubted my past self. Does this mean I get your pay for this PR? 😆

**Comment by Karyum** [comment]
@m4v15 you currently live in a mansion in canada im not sure you need to get paid :stuck_out_tongue_winking_eye:

**Review by des-des — APPROVED** [review]

**Pull request merged**
